---
- name: Ensure all packages are up to date
  hosts: all
  become: yes
  tasks:
    - name: Update all packages (Debian)
      when: ansible_distribution == "Debian"
      apt:
        update_cache: yes
        upgrade: full

- name: Ensure Docker Engine is installed
  hosts: all
  become: yes
  tasks:
    - name: Ensure dependencies are installed (Debian)
      when: ansible_distribution == "Debian"
      apt:
        name: ca-certificates, curl, gpg-agent, software-properties-common
        state: latest
        update_cache: yes

    - name: Ensure Docker PGP key is in APT keyring
      when: ansible_distribution == "Debian"
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Ensure Docker repository is present for APT
      when: ansible_distribution == "Debian"
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable

    - name: Ensure Docker packages are installed
      when: ansible_distribution == "Debian"
      apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: latest

    - name: Ensure the Docker service is enabled and started
      service:
        name: docker
        state: started
        enabled: yes

- name: Ensure Docker Compose (V1) is installed
  hosts: all
  become: yes
  tasks:
    - name: Ensure Python 3 is installed (Debian)
      when: ansible_distribution == "Debian"
      apt:
        name: python3, python3-pip
        state: latest
        update_cache: yes

    - name: Ensure docker-compose is installed through pip
      pip:
        name: docker-compose
        state: latest

- name: Ensure Beets is installed
  hosts: storage
  become: yes
  tasks:
    - name: Ensure Python 3 is installed (Debian)
      when: ansible_distribution == "Debian"
      apt:
        name: python3, python3-pip
        state: latest
        update_cache: yes

    - name: Ensure Beets is installed globally
      pip:
        executable: pip3
        state: latest
        name: beets

- name: Ensure essential tools are installed
  hosts: all
  become: yes
  tasks:
    - name: Ensure essential tools are installed (Debian)
      when: ansible_distribution == "Debian"
      apt:
        name: zsh, mosh, tree, tmux, neovim, rsync, ncdu, htop, git
        state: latest
        update_cache: yes
